### ISSUE TITLE
`remember {..}` calculation block in `VideoPlayer.kt` is called multiple times for the same video

### ISSUE THREAD

**Issue by Onvistlex** [Skyyo/compose-video-playback#2]
Steps to reproduce:
* Add a breakpoint at the following place in VideoPlayer.kt`: 
```
val playerView = remember {
    /*** breakpoint here **/ val layout = LayoutInflater.from(context).inflate(R.layout.video_player, null, false)
    // [..] other code
}
```
* Start the first video
* Debugger stops at the added breakpoint
* Resume the debugger
* Stop the first video
* Start the first video
* Debugger stops again

I assume that it is not intended that the expensive `inflate()` inside of `remember {}` is called more than once for one video?

PS right now I have the same problem and I am looking for a solution. I discovered your slides at https://www.droidcon.com/2021/11/25/video-playback-in-lazycolumn-in-jetpack-compose/ and thought that your approach could be the solution :)

**Comment by Skyyo** [comment]
hi @Onvistlex , does the `playerView` invoke `remember` block again during successful recomposition in the same `CardView` composable? 

Or do you mean there is 1 `playerView` for each `cardView`, and that's the performance issue you experience?

playing with debugger isn't really useful here imo. In other words - try to post a sample where issue is visible, or please provide more details.

If you found a real issue, I'm more than happy to investigate it since there are plenty of bugs in compose, so sooner we find them - sooner we can either avoid them, or assign it as an issue for compose team to fix.

**Comment by Onvistlex** [comment]
Hi, I did a short video:
https://user-images.githubusercontent.com/93600641/173397674-8e7e9d30-0828-4d27-9899-b4880028cc17.mp4
Right now there is no sense for `remember` because the inner block is called every time the `VideoPlayer` composable is used. So the `PlayerView` is not reused it is inflated every time again. This leads to performance issues if it is a complex `AndroidView`.

**Comment by Skyyo** [comment]
`remember` has it's usage, since if recomposition of the `VideoCard` happens during video playback - you won't have to inflate the `playerView` again. 

The reason why `playerView` is recreated each time you play the video again, is because this part:

```kotlin
 if (isPlaying) {
     VideoPlayer(exoPlayer)
 } else {
     VideoThumbnail(videoItem.thumbnail)
           }
```
If you want it to stay consistent - it's easy to do. I've posted what you want on this a new branch, you can find the changes [here](https://github.com/Skyyo/compose-video-playback/commit/990e09eeb6aeab1480cb736517e665db65571816).
Also this approach has it's downsides, you will inflate the player view for each visible card. In my experience that's a much worse hit than inflating the playerView each time you press play.

Ideally, we would want to pass the inflated `playerView` to each card, but it's not that easy to manage all the edge cases there, beginning with last surface frame not being cleared, to reliable  attaching/detaching the playerView from the parent. Feel free to explore this and open a PR @Onvistlex !
